.jbs/VMP.HLS.ManifestLoader.o: Src/VMP.HLS.ManifestLoader.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_HTTP/Src/BFC.HTTP.Answer.h \
  /home/nightly/workarea/VMP_DMS/BFC_HTTP/Src/BFC.HTTP.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.BufferArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_HTTP/Src/BFC.HTTP.Client.h \
  /home/nightly/workarea/VMP_DMS/BFC_HTTP/Src/BFC.HTTP.Answer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPv4Address.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.URL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.URLPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPAddr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPAddrPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Comparable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.ComparablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.NetIface.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.NetIfacePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.URI.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.URLStreamHandler.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  Src/VMP.HLS.LeafManifest.h Src/VMP.HLS.DLL.h \
  Src/VMP.HLS.LeafManifestPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  Src/VMP.HLS.FragmentInfoPtr.h Src/VMP.HLS.Manifest.h \
  Src/VMP.HLS.ManifestPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  Src/VMP.HLS.LevelInfo.h Src/VMP.HLS.LevelInfoPtr.h \
  Src/VMP.HLS.FragmentDataPtr.h Src/VMP.HLS.ManifestDecoder.h \
  Src/VMP.HLS.ManifestDecoderPtr.h Src/VMP.HLS.ManifestLoader.h \
  Src/VMP.HLS.ManifestLoaderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.Thread.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.ThreadPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulCondition.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysLockable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysCondition.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulMutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysMutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.NotOwner.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.WouldDeadLock.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulSynchronizer.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulCS.h \
  Src/VMP.HLS.ProgramInfoPtr.h Src/VMP.HLS.ProgramInfo.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  Src/VMP.HLS.RootManifestPtr.h Src/VMP.HLS.RootManifest.h
