.jbs/VMP.AAC.AudioSpecificConfig.o: Src/VMP.AAC.AudioSpecificConfig.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Utils.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.ConfigInfoRegisterer.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.Libs.Base.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Factory.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.FactoryPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.BuilderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DescrPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.ObjectPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.TypePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Registerer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.RepositoryPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.SimpleBuilder.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.SimpleBuilderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Builder.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Type.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.ConfigInfoRepository.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.ConfigInfoRepositoryPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Repository.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.FactoryArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ObservablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Event.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.EventPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Serializable.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.SerializablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ObserverPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Callback.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.CallbackPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.STL.SHash.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Math.Utils.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.List.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListCell.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Map.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.SortArray.h \
  Src/VMP.AAC.AudioSpecificConfig.h Src/VMP.AAC.DLL.h \
  Src/VMP.AAC.AudioSpecificConfigPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.ConfigInfo.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.ConfigInfoPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Object.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.CounterPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Type.h \
  Src/VMP.AAC.BitStreamPtr.h Src/VMP.AAC.BitStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  Src/VMP.AAC.Defines.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h
