/*
 * File: app/model/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabletGui.model.Login', {
  extend: 'Ext.data.Model',
  alias: 'model.login',

  config: {
		idProperty:'localLoginId',
		identifier:{
  		type:'uuid'
  	},
  	fields:['username','password'],
  	validations:[{
                  field: 'username',
                  type: 'presence',                
                  message: 'Username is required.'
                 },
                 {
          		    field: 'username',
          		    type: 'length',
          		    min: 1,
          		    max: 20,
          		    message: 'Username must be between 1 and 20 characters.'
          			 },
                 {
                  field: 'password',
                  type: 'length',                
                  min:2,
                  message: 'Password is required.'
                 }
          			],
  	proxy:{
  		// Browser restarts don't affect the LocalStorage - the data are preserved
  		type: 'localstorage',
      id: 'loginProxyId'
  	}
  }
});