package com.ipvs.proxy.impl;

import java.util.Random;
public class ProxyConstants {
	
	public static final Random wheel = new Random();
    public static final String STATUS = "status";
    public static final String VERIFY = "Verify";
    public static final String GENERATE = "Generate";
    public static final String SEND = "Send";
    public static final String CONNECT = "Connect";
    public static final String BIND = "Bind";
    public static final String QUIT = "quit";
    public static final String AUTHREQUEST = "AuthorizeStreamRequest";
    public static final String AUTHNOTIFY = "AuthorizeStreamNotification";
    public static final String LISTRESPONSE = "GetStreamListResponse";
    public static final String AUTHRESPONSE = "AuthorizeStreamResponse";
    public static final String LISTREQUEST = "GetStreamListRequest";
    public static final String STARTRECORDINGREQUEST = "StartRecordingRequest";
    public static final String STOPRECORDINGREQUEST = "StopRecordingRequest";
    public static final String UPDATERECORDINGREQUEST = "UpdateRecordingRequest";
    public static final String PAUSERECORDINGREQUEST = "PauseRecordingRequest";
    public static final String RESUMERECORDINGREQUEST = "ResumeRecordingRequest";
    public static final String RECORDINGSTATUSREQUEST = "RecordingStatusRequest";
    public static final String CREATEBOOKMARKREQUEST = "CreateBookmarkRequest";
    public static final String MEDIATIMESTAMPREQUEST = "MediaTimestampRequest";
    public static final String AUTHORIZATIONUPDATEREQUEST = "AuthorizationUpdateRequest";
    public static final String HEARTBEAT = "HeartBeat";
    public static final String SEPERATOR = "|";
    public static final String RECORDINGNOTIFICATION = "RecordingNotification";
    public static final String XSDFILE = "/com/ipvs/xsd/ipvs_stxs_interface.xsd";
    public static final String XMLFILEPATH = "/com/ipvs/proxy/xml/";
    public static final String MEDIAROOM_XMLFILEPATH = "/com/ipvs/mediaroomservice/xml/";
    public static final String SYSTEM_XMLFILEPATH = "/com/ipvs/systemservice/xml/";
    public static final String ASSET_XMLFILEPATH = "/com/ipvs/assetadminservice/xml/";
    public static final String TITLE = "ocprecordingtitle";
    public static final int CASE_STARTRECORDINGREQUEST = 1;
    public static final int CASE_STOPRECORDINGREQUEST = 2;
    public static final int CASE_UPDATERECORDINGREQUEST = 3;
    public static final int CASE_PAUSERECORDINGREQUEST = 4;
    public static final int CASE_RESUMERECORDINGREQUEST = 5;
    public static final int CASE_RECORDINGSTATUSREQUEST = 6;
    public static final int CASE_CREATEBOOKMARKREQUEST = 7;
    public static final int CASE_MEDIATIMESTAMPREQUEST = 8;
    public static final int CASE_LISTREQUEST = 9;
    public static final int CASE_AUTHORIZATIONUPDATEREQUEST = 10;
    public static final String STARTRECORDINGRESPONSE = "StartRecordingResponse";
    public static final String STOPRECORDINGRESPONSE = "StopRecordingResponse";
    public static final String PAUSERECORDINGRESPONSE = "PauseRecordingResponse";
    public static final String RESUMERECORDINGRESPONSE = "ResumeRecordingResponse";
    public static final String UPDATERECORDINGRESPONSE = "UpdateRecordingResponse";
    public static final String RECORDINGSTATUSRESPONSE = "RecordingStatusResponse";
    public static final String CREATEBOOKMARKRESPONSE = "CreateBookmarkResponse";
    public static final String MEDIATIMESTAMPRESPONSE = "MediaTimestampResponse";
    public static final String AUTHORIZATIONUPDATERESPONSE = "AuthorizationUpdateResponse";
    public static final String PROXY_XMLFILEPATH = "/com/ipvs/mediaroomservice/xml/";
    public static final boolean ENABLE_DISCONNECT = false;
	public static final String RECORD_STARTED = "RecordStarted";
	public static final String RECORD_PAUSED = "RecordPaused";
	public static final String RECORD_STOPPED = "RecordStopped";
	public static final String RECORD_RESUMED = "RecordResumed";
	public static final String STREAM_START_REQUEST = "StreamStartRequest";
	public static final String STREAM_STOPPED = "StreamStopped";
	public static final String USER_PRESENCE = "UserPresence";
	public static final String STREAM_STARTED = "StreamStarted";
	public static final String ADD_TRACK_ACTION_REQUEST = "AddTrackActionRequest";
	public static final String ADD_STREAM_ACTION_REQUEST = "AddStreamActionRequest";
	public static final String DELETE_MEDIAROOM_REQUEST = "DeleteMediaRoomRequest";
	public static final String ProxyHOSTNAMEPATH = "//ClientApp[@name='IPVSPROXY']/proxyServerIP";
	public static final String ProxyPORTPATH = "//ClientApp[@name='IPVSPROXY']/port";
	public static final String SOURCE_TITLE = "//ClientApp[@name='IPVSPROXY']/title";
	public static final String HEARTBEAT_FREQUENCY = "//ClientApp[@name='IPVSPROXY']/heartbeatFrequency";
	public static final String ProxyDevice = "ProxyDevice";
	//public static final String DESTINATION_EVENT = "DestinationEvent";
	public static final String RECORDING_PAUSED = "102";
	public static final String RECORDING_STARTED = "101";
	public static final int STATE_CONNECTED = 1;
	public static final int STATE_DISCONNECTED = 0;
	public static final int STATE_CANCELLED = 2;
	public static final String RECORDING_ERROR = "103";
	public static final String SERVER_DISCONNECTED = "SERVER_DISCONNECTED";

}
