.jbs/VMP.AVC.Frame.o: Src/VMP.AVC.Frame.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ProxyDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Device.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DevicePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.BrokenPipe.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.EndOfStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.WouldBlock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Aliasing.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.FrameFactory.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.Libs.Base.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.Frame.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.FramePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Cloneable.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Object.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.ObjectPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.CounterPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.TypePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Type.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DescrPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Serializable.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.SerializablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.Picture.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUser.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUserPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.ListPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VEnumPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VFloatPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VIntPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.Plane.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PlaneFormat.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.ColorChannel.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.ColorSpace.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PlaneFormatManifest.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PlaneFormatRegistry.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Block.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Branch.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Data.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Reader.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Int24.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Uint24.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Block.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Writer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Reader.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PictureFormat.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.TEnumPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PictureFormatManifest.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.FourCCArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Image/Src/BFC.Image.PictureFormatRegistry.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.AudioFrame.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.AudioFramePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Sound/Src/BFC.Sound.BlockPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Sound/Src/BFC.Sound.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Sound/Src/BFC.Sound.FormatPtr.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.BytesFrame.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.BytesFramePtr.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.VideoFrame.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.VideoFramePtr.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.FrameFactoryRegistry.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.Mutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulSynchronizer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysMutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.NotOwner.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysLockable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.WouldDeadLock.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.Lockable.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.NotLocked.h \
  Src/VMP.AVC.NALU.h Src/VMP.AVC.DLL.h Src/VMP.AVC.NALUPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  Src/VMP.AVC.Frame.h Src/VMP.AVC.FramePtr.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.BytesFrame.h
