package com.ipvs.policyadminservice.utils;

public class MediaRoomRuleKey {
	  public static final String MEDIAROOM_RULE_ADDMEDIA_USER = "MEDIAROOM_RULE_ADDMEDIA_USER";
	  public static final String MEDIAROOM_RULE_ADDSTREAM_USER = "MEDIAROOM_RULE_ADDSTREAM_USER";
	  public static final String MEDIAROOM_RULE_CONFCREATE_USER = "MEDIAROOM_RULE_CONFCREATE_USER";
	  public static final String MEDIAROOM_RULE_CONFSTART_USER = "MEDIAROOM_RULE_CONFSTART_USER";
	  public static final String MEDIAROOM_RULE_STREAM_DST_RESOURCE = "MEDIAROOM_RULE_STREAM_DST_RESOURCE";
	  public static final String MEDIAROOM_RULE_STREAM_DST_USER = "MEDIAROOM_RULE_STREAM_DST_USER";
	  public static final String MEDIAROOM_RULE_STREAM_PROFILE = "MEDIAROOM_RULE_STREAM_PROFILE";
	  public static final String MEDIAROOM_RULE_STREAM_SRC_RESOURCE = "MEDIAROOM_RULE_STREAM_SRC_RESOURCE";
	  public static final String MEDIAROOM_RULE_STREAM_SRC_USER = "MEDIAROOM_RULE_STREAM_SRC_USER";
	  public static final String MEDIAROOM_RULE_TARGET_MEDIAROOM = "MEDIAROOM_RULE_TARGET_MEDIAROOM";
	  public static final String MEDIAROOM_RULE_STREAM_RELAY_RESOURCE = "MEDIAROOM_RULE_STREAM_RELAY_RESOURCE";
}
