.jbs/BFC.Image.Picture.o: Src/BFC.Image.Picture.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ProxyDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Device.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DevicePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.BrokenPipe.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.EndOfStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.WouldBlock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Aliasing.h \
  Src/BFC.Image.ConverterManager.h Src/BFC.Image.DLL.h \
  Src/BFC.Image.ConverterManagerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.List.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListCell.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Matrix.h \
  Src/BFC.Image.ConverterPtr.h Src/BFC.Image.ConverterStrategyPtr.h \
  Src/BFC.Image.ConverterStrategy.h Src/BFC.Image.PictureFormat.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.TEnumPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  Src/BFC.Image.ColorChannel.h Src/BFC.Image.ColorSpace.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  Src/BFC.Image.PictureFormatManifest.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUser.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUserPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.ListPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VEnumPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VFloatPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VIntPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  Src/BFC.Image.PlaneFormatManifest.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.FourCCArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  Src/BFC.Image.PictureFormatRegistry.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  Src/BFC.Image.PlaneFormat.h Src/BFC.Image.PlaneFormatRegistry.h \
  Src/BFC.Image.Picture.h Src/BFC.Image.Plane.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Block.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Branch.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Data.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Reader.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Int24.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Uint24.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Block.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Writer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.Reader.h
