\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestLoginRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestSetServiceDomainRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\systemservice\xml\InitializeDBRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetSourceListRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetStreamProfileListRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\AddMediaRoomRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\AddMediaSourceRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\AddStreamRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\AddStreamActionRequest.xml
#sleep=1
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomNIDRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomNIDRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\DeleteMediaRoomRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomNIDRequest.xml

#Create Connection test
\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestLoginRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestSetServiceDomainRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\CreateConnectionRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\AddStreamActionRequest.xml
#sleep=1
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomNIDRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetMediaRoomNIDRequest.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\DeleteMediaRoomRequest.xml

# Test StreamProfile
\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestLoginRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\test\xml\miyertestSetServiceDomainRequest.xml 
\miyer\work\mediaroom\src\com\ipvs\systemservice\xml\InitializeDBRequest.xml
#\miyer\work\mediaroom\src\com\ipvs\assetadminservice\xml\V2DMediaStreamProfile_BASE_ALL_ADD.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetStreamProfileListRequest.xml
\miyer\work\mediaroom\src\com\ipvs\assetadminservice\xml\AssetResource_BASE_ALL_ADD.xml
\miyer\work\mediaroom\src\com\ipvs\assetadminservice\xml\MediaStreamSrcPortResource_BASE_ALL_ADD.xml
\miyer\work\mediaroom\src\com\ipvs\mediaroomservice\xml\GetSourceListRequest.xml
