.jbs/VMP.M4S.SLConfigDescriptor.o: Src/VMP.M4S.SLConfigDescriptor.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Utils.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ProxyDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Device.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DevicePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.BrokenPipe.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.EndOfStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.WouldBlock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.MemoryInputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.FinalDevice.h \
  Src/VMP.M4S.Defines.h Src/VMP.M4S.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  Src/VMP.M4S.SLConfigDescriptor.h Src/VMP.M4S.SLConfigDescriptorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h
