#!/bin/sh
#
#
# Description:	wrapper of OCF RA msctlimpl, based on original heartbeat RA.
#		See OCF RA msctlimpl for more information.
#
#
#	This script manages msctl
#	usage: $0 ... {start|stop|status|monitor}
#

. /etc/ha.d/resource.d//hto-mapfuncs

ipvs_ra_execocf(){
    if [ "x${1}" = "x" ]; then
	log_and_print "ERROR: No action specfied."
	usage
	exit 1
    fi

    . ${OCF_RA_DIR}/heartbeat/.ocf-shellfuncs
    
    __ACTION=$1
    __SCRIPT_NAME="${OCF_RA_DIR}/ipvs/${OCF_TYPE}"
    
    if [ "x${OCF_TYPE}" = "x" ]; then
	log_and_print "ERROR: Internal error. No value for OCF_TYPE specified"
	exit 1
    fi
    
    if [ ! -x $__SCRIPT_NAME ] 
    then
	log_and_print "ERROR: $__SCRIPT_NAME is not an executable file "
	exit 1
    fi

    # execute ocf ra and get return value
    case $__ACTION in
	start)		$__SCRIPT_NAME start;;
	stop)		$__SCRIPT_NAME stop ;;
	monitor)	$__SCRIPT_NAME monitor;;
	status)		$__SCRIPT_NAME monitor;;	# Mapping this to monitor is a bug
	
	usage|help)	usage;;
	*)		log_and_print "ERROR: Unknown operation: $__ACTION"
			usage
			exit 1;;
    esac
    
    ocf_return_status=$?
    case $ocf_return_status in
	$OCF_SUCCESS)
              case $__ACTION in
		  monitor|status)	log_and_print "INFO: $rsc_type Running OK";;
		  *)			log_and_print "INFO: $rsc_type Success";;
	      esac;;

	$OCF_ERR_GENERIC)
		log_and_print "ERROR: $rsc_type Generic error";;

	$OCF_ERR_ARGS)
		log_and_print "ERROR: $rsc_type Illegal argument";;

	$OCF_ERR_UNIMPLEMENTED)
		log_and_print "ERROR: $rsc_type Function unimplemented";;

	$OCF_ERR_PERM)
		log_and_print "ERROR: $rsc_type User had insufficient privilege";;

	$OCF_ERR_INSTALLED)
		log_and_print "ERROR: $rsc_type Program is not installed";;

	$OCF_ERR_CONFIGURED)
		log_and_print "ERROR: $rsc_type Program is not configured";;

	$OCF_NOT_RUNNING)
		log_and_print "INFO: $rsc_type Resource is stopped";;
	*)
		log_and_print "ERROR: $rsc_type Unknown error: $ocf_return_status"
		exit 1
		;;
	esac

	return $ocf_return_status
}

usage() {
    echo "usage: $0 [primary | secondary] $LEGAL_ACTIONS"
    exit 1
}

if [ $# != 1 ]; then
    usage
fi

OCF_TYPE=msctlimpl
OCF_RESOURCE_INSTANCE=${OCF_TYPE}
export OCF_TYPE OCF_RESOURCE_INSTANCE 

ipvs_ra_execocf $1
