.jbs/VMP.L3.EncoderBackend.o: Src/VMP.L3.EncoderBackend.cpp \
  Src/VMP.L3.EncoderBackend.h Src/VMP.L3.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  Src/VMP.L3.Backend.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUser.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarUserPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.ListPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VEnumPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VFloatPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VIntPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VarPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ObserverPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Callback.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.CallbackPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.EventPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Event.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Serializable.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.SerializablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteOutputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ObservablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.STL.SHash.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Math.Utils.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.List.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListCell.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Object.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.ObjectPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.CounterPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.TypePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Type.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.DescrPtr.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.DynVar.h \
  /home/nightly/workarea/VMP_DMS/VMP/Src/VMP.Libs.Base.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.VBufferPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.TBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.Type.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.TypePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Cloneable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Dyn/Src/BFC.Dyn.Var.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Serializable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Invokable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.InvokablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.RequestPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ResultPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.BufferArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.IElement.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.ValueEvent.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Msg/Src/BFC.Msg.Observer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.BufferArray.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.IElementPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.IToolkitPtr.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.UObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_DL/Src/BFC.DL.Object.h \
  /home/nightly/workarea/VMP_DMS/VMP_UI/Src/VMP.UI.IElement.h
