/*
 * File: app/store/Setup.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabletGui.store.Setup', {
  extend: 'Ext.data.Store',
  alias: 'store.setup',
   
	config: {
    model: 'TabletGui.model.Setup',
    storeId: 'settingsStoreId',
    autoSync:true,
    autoLoad:true
  }     
    /*  
    //auto call load after creation
    autoLoad:true,
    //auto sync the sotre with proxy after each edit record
    autoSync:true,
    */    
});