.jbs/BFC.Net.Log.Handler.o: Src/BFC.Net.Log.Handler.cpp \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Light.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.DataSharer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Mem.AllocatorPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrDecl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrHub.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ArrayBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ConsoleColor.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.Debugger.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DebuggerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtrImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ColoredBuffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.Console.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ByteInputStreamPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FourCC.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Endian.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.UUId.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.System.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.CompArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.ProxyDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.Device.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.DevicePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.ThreadFinderPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.BrokenPipe.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.EndOfStream.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.WouldBlock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.File.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.FilePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.FinalDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_VFS/Src/BFC.VFS.FSPath.h \
  /home/nightly/workarea/VMP_DMS/BFC_VFS/Src/BFC.VFS.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.BufferArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.List.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListTmpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListBase.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.ListCell.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.TCPSocket.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.TCPSocketPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPv4Address.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.FastCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.SockAddr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.SockAddrPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.Address.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.AddressPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Comparable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.ComparablePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPAddr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPAddrPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.Array.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.IPImpl.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.NetIface.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.NetIfacePtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.Socket.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.SocketPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_IO/Src/BFC.IO.FinalDevice.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.MACAddress.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.PacketPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.TL.BufferArray.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Delta.h \
  Src/BFC.Net.Log.Handler.h Src/BFC.Net.Log.DLL.h \
  Src/BFC.Net.Log.HandlerPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.Thread.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.DLL.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.ThreadPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.SPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Buffer.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Exception.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Debug.DObject.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulCondition.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysLockable.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Base.Types.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysCondition.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulMutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.SysMutex.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.NotOwner.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.WouldDeadLock.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulSynchronizer.h \
  /home/nightly/workarea/VMP_DMS/BFC_MT/Src/BFC.MT.EmulCS.h \
  /home/nightly/workarea/VMP_DMS/BFC_Net/Src/BFC.Net.TCPSocketPtr.h \
  /home/nightly/workarea/VMP_DMS/BFC_Light/Src/BFC.Time.Clock.h
