/*
 * File: app/model/Setup.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TabletGui.model.Setup', {
  extend: 'Ext.data.Model',
  alias: 'model.setup',

  config: {
		idProperty:'localSettingsId',
		identifier:{
  		type:'uuid'
  	},
    fields: ['serverip', 'clientid'],
    validations:[
              	 {
                  type: 'format',
                  field: 'serverip',
                  //matcher:/\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/
                  //matcher:/^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])$/
                  //this is the best IP validation others can't validate 1.1.1.1.123
                  matcher:/^(([01]?[0-9]?[0-9]|2([0-4][0-9]|5[0-5]))\.){3}([01]?[0-9]?[0-9]|2([0-4][0-9]|5[0-5]))$/
                 },
                 {
                  type: 'presence',
                  field: 'clientid',
                  message: 'Client ID is required.'
                 }
              ],
    proxy: {
      type: 'localstorage',
      id: 'settingsProxyId'
    }      
  }

});